#

# Keys under which options are stored.
OPTIONS_UNKNOWN = 0
OPTIONS_FILE_OUTPUT = 1
OPTIONS_CPU = 2
OPTIONS_STANDARD = 3

# General options that belong to no specific collection.
OPTION_UNKNOWN = 0
OPTION_DISABLE_OPTIMISATIONS = 1

# CPU optons.
CPU_UNKNOWN = 0
CPU_MC60000 = 1
CPU_MC60010 = 2
CPU_MC60020 = 3
CPU_MC60030 = 4
CPU_MC60040 = 5
CPU_MC60060 = 7

ASM_SYNTAX_UNKNOWN = 0
ASM_SYNTAX_MOTOROLA = 1

OUTPUT_FORMAT_UNKNOWN = 0
OUTPUT_FORMAT_BINARY = 1
OUTPUT_FORMAT_AMIGA_HUNK = 2
OUTPUT_FORMAT_ATARIST_TOS = 3
